---
# Limits how many jobs globally can be run concurrently.
# The most upper limit of jobs using all defined runners
gitlab_runner_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"

gitlab_runner_concurrent: '{{ ansible_processor_cores }}'

# Defines in seconds how often to check GitLab for a new builds
gitlab_runner_check_interval: 0

# GitLab coordinator URL
gitlab_runner_coordinator_url: 'https://gitlab.local/'

gitlab_runner_connect_enable: false 

# Path to coordinator cert on local machine
# Define this if you are using Self-Signed cert for gitlab
# https://gitlab.com/gitlab-org/gitlab-runner/blob/master/docs/configuration/tls-self-signed.md
gitlab_runner_coordinator_cert_path: 'gitlab.local.crt'

# GitLab registration token, keep it empty if you dont want to register it
gitlab_runner_registration_token: ''

# Runner name (not used, just informatory)
gitlab_runner_name: '{{ ansible_hostname }}'

# Runner tags
gitlab_runner_tags: []

# Directory where builds and caches will be stored in context of selected executor
# (Locally, Docker, SSH)
gitlab_runner_persistent_dir: "/etc/gitlab-runner"

# Gitlab-runner registration variables
gitlab_runner_shell_register_script: "gitlab-runner-shell-register.sh"
gitlab_runner_docker_register_script: "gitlab-runner-docker-register.sh"

gitlab_runner_docker_name: "docker-runner"
gitlab_runner_docker_image: "docker:stable"
gitlab_runner_docker_tags: [docker,]


docker_registry_hostname: gitlab.local
docker_registry_port: 4567
docker_registry_cert_path: "/etc/docker/certs.d/{{docker_registry_hostname}}:{{docker_registry_port}}/"
